name: Restore dotnet
description: Restore the dotnet solution
author: AceOfKestrels

inputs:
    solution-path:
        description: "The path to the .sln file relative to the repository root"
        required: false
        default: .

runs:
    using: composite
    steps: 
      - name: "Install dependencies"
        shell: bash
        env:
            SLN_PATH: ${{ inputs.solution-path }}
        run: dotnet restore --verbosity normal "$SLN_PATH"