name: Commit git changes
description: Commit all changes made in the repository and push them back to the origin branch
author: AceOfKestrels

inputs:
    commit-message:
        description: "The commit message"
        required: true

runs:
    using: composite
    steps: 
      - name: "Commit changes"
        shell: bash
        env:
            COMMIT_MESSAGE: ${{ inputs.commit-message }}
            NIX_CONFIG: "experimental-features = nix-command flakes"
        run: |
            echo "This repository is deprecated."
            echo "Workflows are now located at KestrelsDevelopment/Workflows"
            exit 1