name: Test dotnet
description: Test the dotnet solution
author: AceOfKestrels

inputs:
    restore:
        description: "Whether to restore dependencies prior to building (implies build: true)"
        required: false
        default: false
    build:
        description: "Whether to build the solution prior to running tests"
        required: false
        default: false
    solution-path:
        description: "The path to the .sln file relative to the repository root"
        required: false
        default: .
    configuration:
        description: "The configuration to use for the build"
        required: false
        default: Release

runs:
    using: composite
    steps: 
      - name: "Install dependencies"
        if: ${{ inputs.restore == true }}
        uses: KestrelsDevelopment/.github/.github/actions/dotnet-restore@main
        with:
            solution-path: ${{ inputs.solution-path }}

      - name: "Build solution"
        if: ${{ inputs.restore == true || inputs.build == true }}
        shell: bash
        env:
            SLN_PATH: ${{ inputs.solution-path }}
            BUILD_CONF: ${{ inputs.configuration }}
        run: dotnet build --no-restore --verbosity normal --configuration "$BUILD_CONF" "$SLN_PATH"

      - name: "Run tests"
        shell: bash
        env:
            SLN_PATH: ${{ inputs.solution-path }}
            BUILD_CONF: ${{ inputs.configuration }}
        run: dotnet test --no-build --verbosity normal --configuration "$BUILD_CONF" "$SLN_PATH"