name: "Update Flake"

on:
    workflow_call:
        inputs:
            flake-path:
                description: Path to the flake (relative to repo root)
                required: false
                type: string
                default: .

permissions:
    contents: write

jobs:
    update:
        name: Update flake
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v3

          - name: Install Nix
            uses: cachix/install-nix-action@v31
            with:
                nix_path: nixpkgs=channel:nixos-unstable

          - name: Update lockfile
            uses: KestrelsDevelopment/.github/.github/actions/nix-update-flake@main
            with:
                flake-path: ${{ inputs.flake-path }}

          - name: Commit changes
            uses: KestrelsDevelopment/.github/.github/actions/git-commit-changes@main
            with:
                commit-message: "[chore] Update flake lock"