name: "Nix CI"

on:
    workflow_call:

permissions:
    contents: read

jobs:
    build:
        uses: KestrelsDevelopment/.github/.github/workflows/build.nix@main
    lint:
        uses: KestrelsDevelopment/.github/.github/workflows/lint.nix@main